config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index", as: :about
  
  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"

  get "password/forgot", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset", to: "password_resets#edit"
  patch "password/reset", to: "password_resets#update"

  get "signup", to: "registrations#new"
  post "signup", to: "registrations#create"

  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"

  delete "signout", to: "sessions#destroy"

  post '/auth/twitter/callback', to: "omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets

  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 1.hours.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: @tweet.publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual
class User < ApplicationRecord
  has_many :twitter_accounts
  has_many :tweets
  
  has_secure_password

  validates :email, uniqueness: true, presence: true, format: {
    with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, message: 'must be a valid email address'
  }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to signin_path, alert: "You must be signed in to do that." if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks.rb
class OmniauthCallbacks < ApplicationController
  def twitter
    acc = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
    acc.update(
      name: auth.info.name,
      username: auth.info.nickname,
      image: auth.info.image,
      token: auth.credentials.token,
      secret: auth.credentials.secret,
    )
    redirect_to twitter_accounts_path, notice: "@#{auth.info.nickname} twitter account connected!"
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_later
    end
    
    redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password"
  end

  def edit
    begin
      @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to signin_path, alert: "Your token has expired, please try again."
    end
  end

  def update
    begin
      @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to signin_path, alert: "Your token has expired, please try again."
    end
    if @user.update(password_params)
        redirect_to signin_path, notice: "Your password was reset successfully, please sign in."
    else
      render :edit
    end
  end

  private
  
  def password_params
    params.require(:user).permit(:password, :password_confirm)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.authenticate(params[:user][:current_password])
      if Current.user.update(password_params)
        redirect_to root_path, notice: "Password updated!"
      end
    else
      redirect_to edit_password_path, alert: "Incorrect password"
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    puts @user.errors
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account"
    else
      render :new, status: 400
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    # user.authenticate comes from has_secure_password
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new, status: 401
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Succesfully logged out"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.create(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: "Tweet was scheduled successfully"
    else
      render :new, 400
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "Tweet was edited successfully"
    else
      render :edit
    end  
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "Tweet was unscheduled"
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_twitter_account, only: [:destroy]

  def index
    @twitter_accounts = Current.user.twitter_accounts
  end

  def destroy
    @twitter_account.destroy
    redirect_to twitter_accounts_path, notice: "Account @#{@twitter_account.username} removed"
  end

  private

  def set_twitter_account
    @twitter_account = Current.user.twitter_accounts.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex col align-items-center justify-content-between mt-4">
  <h1>Welcome to scheduled tweets</h1>
  <%= link_to "Connect Twitter", "/auth/twitter", method: :post, class: "btn btn-primary" %>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_path(token: params[:token]) do |form| %>
<% if form.object and form.object.errors.any? %>
    <div class="alert alert-danger">
      <%= form.object.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", placeholder: "password" %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
  </div>
  <div>
    <%= form.submit "Confirm New Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path, method: :post do |form| %>
  <div class="mb-3">
    <%= form.label :email%>
    <%= form.email_field :email, class: "form-control", placeholder: "johndoe@example.com" %>
  </div>
  <div>
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
  <div class="alert alert-danger">
    <%= form.object.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>

        <% if Current.user %>
        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto mb-lg-0">
      <% if Current.user %>
        <li>
          <p class="mb-0"><%= link_to Current.user.email, edit_password_path, class: "nav-link" %></p>
        </li>
        <li class="nav-item">
          <%= button_to "Signout", signout_path, method: :delete, class: "btn btn-outline-secondary" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Signin", signin_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Signup", signup_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<%= form_with model: @tweet do |form| %>
  <%= render "shared/form_errors", form: form %>
  
  <div class="mb-3">
    <%= form.label :twitter_account_id %>
    <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: "form-control" } %>
    <%= link_to "Connect your twitter account", "/auth/twitter", method: :post, class: "btn btn-link" %>
  </div>

  <div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :publish_at %>
    <%= form.datetime_select :publish_at %>
  </div>

  <%= form.button "Schedule", class: "btn btn-primary" %>

  <% if form.pbject.persisted? %>
    <%= link_to "Delete", form.object, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
  <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body">
  <%= tweet.body %>
  <div class="me-4>
  <%= image_tag tweet.twitter_account.image, class: "rounded-circle" %>
  <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: "_blank" %>

    <% if tweet.published? %>
      <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}" %>
    <% else %>
      Scheduled for <%= l tweet.publish_at, format: :short %>
      <%= link_to, edit_tweet_path(tweet) %>
    <% end %>
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Scheduled Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center mt-4">
  <h1>Tweets</h1>

  <% if Current.user.twitter_accounts.any? %>
    <%= link_to "Schedule a Tweet", new_tweet_path, class: "btn btn-primary" %>
  <% else %>
    <%= link_to "Connect your twitter account", "/auth/twitter", method: :post, class: "btn btn-primary"%>
  <% end %>
</div>

<%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule a Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between">
  <h1>Twitter Accounts</h1>
  <%= link_to "Connect a Twitter account", "/auth/twitter", method: :post, class: "btn btn-primary" %>
</div>

<%= @twitter_accounts.each do |acc| %>
  <div class="d-flex align-items-center mb-4">
    <%= image_tag acc.image, class: "rounded-circle" %>
    <%= link_to "@#{acc.username}", "https://twitter.com/#{acc.username}", target: "_blank" %>
  </div>

  <%= button_to "Disconnect", acc, method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>